---
title: "git_01"
author: "Eric Soto"
date: "September 10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves.  
Did gyre and gimble in the wabe;  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
  
“Beware the Jabberwock, my son!  
   
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,    
And sorry I could not travel both.   
And be one traveler, long I stood.   
And looked down one as far as I could.   
To where it bent in the undergrowth;   
   
Then took the other, just as fair,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"I like the Walrus best," said Alice: "because you see he was a little sorry for the poor oysters."   
"He ate more than the Carpenter, though," said Tweedledee. "You see he held his handkerchief in front, so that the Carpenter couldn't count how many he took: contrariwise."    
  
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
One fish, Two fish, Red fish, Blue fish,   
Black fish, Blue fish, Old fish, New fish.   
This one has a littlecar.   
This one has a little star.  
Say! What a lot of fish there are.  
Yes. Some are red, and some are blue.  
Some are old and some are new.  
Some are sad, and some are glad,  
And some are very, very bad.  
Why are they sad and glad and bad?  
  